apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec: 
      containers:
        - name: movies
          image: fabricioveronez/rotten-potatoes:23
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: movies-configmap
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD